// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yaorm_controller.proto

package org.roylance.yaorm;

public final class YaormController {
  private YaormController() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommonActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaorm.CommonAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
     */
    org.roylance.yaorm.YaormModel.UIYaormRequest getRequest();
    /**
     * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
     */
    org.roylance.yaorm.YaormModel.UIYaormRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
     */
    org.roylance.yaorm.YaormModel.UIYaormResponse getResponse();
    /**
     * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
     */
    org.roylance.yaorm.YaormModel.UIYaormResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code org.roylance.yaorm.CommonAction}
   */
  public  static final class CommonAction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaorm.CommonAction)
      CommonActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommonAction.newBuilder() to construct.
    private CommonAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonAction() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommonAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.roylance.yaorm.YaormModel.UIYaormRequest.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(org.roylance.yaorm.YaormModel.UIYaormRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.roylance.yaorm.YaormModel.UIYaormResponse.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(org.roylance.yaorm.YaormModel.UIYaormResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_CommonAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_CommonAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaorm.YaormController.CommonAction.class, org.roylance.yaorm.YaormController.CommonAction.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private org.roylance.yaorm.YaormModel.UIYaormRequest request_;
    /**
     * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
     */
    public org.roylance.yaorm.YaormModel.UIYaormRequest getRequest() {
      return request_ == null ? org.roylance.yaorm.YaormModel.UIYaormRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
     */
    public org.roylance.yaorm.YaormModel.UIYaormRequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private org.roylance.yaorm.YaormModel.UIYaormResponse response_;
    /**
     * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
     */
    public org.roylance.yaorm.YaormModel.UIYaormResponse getResponse() {
      return response_ == null ? org.roylance.yaorm.YaormModel.UIYaormResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
     */
    public org.roylance.yaorm.YaormModel.UIYaormResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (response_ != null) {
        output.writeMessage(2, getResponse());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaorm.YaormController.CommonAction)) {
        return super.equals(obj);
      }
      org.roylance.yaorm.YaormController.CommonAction other = (org.roylance.yaorm.YaormController.CommonAction) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaorm.YaormController.CommonAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaorm.YaormController.CommonAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaorm.CommonAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaorm.CommonAction)
        org.roylance.yaorm.YaormController.CommonActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_CommonAction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_CommonAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaorm.YaormController.CommonAction.class, org.roylance.yaorm.YaormController.CommonAction.Builder.class);
      }

      // Construct using org.roylance.yaorm.YaormController.CommonAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_CommonAction_descriptor;
      }

      @java.lang.Override
      public org.roylance.yaorm.YaormController.CommonAction getDefaultInstanceForType() {
        return org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance();
      }

      @java.lang.Override
      public org.roylance.yaorm.YaormController.CommonAction build() {
        org.roylance.yaorm.YaormController.CommonAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.roylance.yaorm.YaormController.CommonAction buildPartial() {
        org.roylance.yaorm.YaormController.CommonAction result = new org.roylance.yaorm.YaormController.CommonAction(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaorm.YaormController.CommonAction) {
          return mergeFrom((org.roylance.yaorm.YaormController.CommonAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaorm.YaormController.CommonAction other) {
        if (other == org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaorm.YaormController.CommonAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaorm.YaormController.CommonAction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.roylance.yaorm.YaormModel.UIYaormRequest request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormModel.UIYaormRequest, org.roylance.yaorm.YaormModel.UIYaormRequest.Builder, org.roylance.yaorm.YaormModel.UIYaormRequestOrBuilder> requestBuilder_;
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      public org.roylance.yaorm.YaormModel.UIYaormRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? org.roylance.yaorm.YaormModel.UIYaormRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      public Builder setRequest(org.roylance.yaorm.YaormModel.UIYaormRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      public Builder setRequest(
          org.roylance.yaorm.YaormModel.UIYaormRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      public Builder mergeRequest(org.roylance.yaorm.YaormModel.UIYaormRequest value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              org.roylance.yaorm.YaormModel.UIYaormRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      public org.roylance.yaorm.YaormModel.UIYaormRequest.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      public org.roylance.yaorm.YaormModel.UIYaormRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              org.roylance.yaorm.YaormModel.UIYaormRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormRequest request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormModel.UIYaormRequest, org.roylance.yaorm.YaormModel.UIYaormRequest.Builder, org.roylance.yaorm.YaormModel.UIYaormRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaorm.YaormModel.UIYaormRequest, org.roylance.yaorm.YaormModel.UIYaormRequest.Builder, org.roylance.yaorm.YaormModel.UIYaormRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private org.roylance.yaorm.YaormModel.UIYaormResponse response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormModel.UIYaormResponse, org.roylance.yaorm.YaormModel.UIYaormResponse.Builder, org.roylance.yaorm.YaormModel.UIYaormResponseOrBuilder> responseBuilder_;
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      public org.roylance.yaorm.YaormModel.UIYaormResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? org.roylance.yaorm.YaormModel.UIYaormResponse.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      public Builder setResponse(org.roylance.yaorm.YaormModel.UIYaormResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      public Builder setResponse(
          org.roylance.yaorm.YaormModel.UIYaormResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      public Builder mergeResponse(org.roylance.yaorm.YaormModel.UIYaormResponse value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              org.roylance.yaorm.YaormModel.UIYaormResponse.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      public org.roylance.yaorm.YaormModel.UIYaormResponse.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      public org.roylance.yaorm.YaormModel.UIYaormResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              org.roylance.yaorm.YaormModel.UIYaormResponse.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>.org.roylance.yaorm.UIYaormResponse response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormModel.UIYaormResponse, org.roylance.yaorm.YaormModel.UIYaormResponse.Builder, org.roylance.yaorm.YaormModel.UIYaormResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaorm.YaormModel.UIYaormResponse, org.roylance.yaorm.YaormModel.UIYaormResponse.Builder, org.roylance.yaorm.YaormModel.UIYaormResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaorm.CommonAction)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaorm.CommonAction)
    private static final org.roylance.yaorm.YaormController.CommonAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaorm.YaormController.CommonAction();
    }

    public static org.roylance.yaorm.YaormController.CommonAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonAction>
        PARSER = new com.google.protobuf.AbstractParser<CommonAction>() {
      @java.lang.Override
      public CommonAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonAction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonAction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonAction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.roylance.yaorm.YaormController.CommonAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface YaormMainControllerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaorm.YaormMainController)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
     */
    boolean hasGetSchemas();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
     */
    org.roylance.yaorm.YaormController.CommonAction getGetSchemas();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
     */
    org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetSchemasOrBuilder();

    /**
     * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
     */
    boolean hasGetTables();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
     */
    org.roylance.yaorm.YaormController.CommonAction getGetTables();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
     */
    org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTablesOrBuilder();

    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
     */
    boolean hasGetTableDefinition();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
     */
    org.roylance.yaorm.YaormController.CommonAction getGetTableDefinition();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
     */
    org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTableDefinitionOrBuilder();

    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
     */
    boolean hasGetTableDefinitions();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
     */
    org.roylance.yaorm.YaormController.CommonAction getGetTableDefinitions();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
     */
    org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTableDefinitionsOrBuilder();

    /**
     * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
     */
    boolean hasGetRecordCount();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
     */
    org.roylance.yaorm.YaormController.CommonAction getGetRecordCount();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
     */
    org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetRecordCountOrBuilder();

    /**
     * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
     */
    boolean hasGetRecords();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
     */
    org.roylance.yaorm.YaormController.CommonAction getGetRecords();
    /**
     * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
     */
    org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetRecordsOrBuilder();
  }
  /**
   * Protobuf type {@code org.roylance.yaorm.YaormMainController}
   */
  public  static final class YaormMainController extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaorm.YaormMainController)
      YaormMainControllerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use YaormMainController.newBuilder() to construct.
    private YaormMainController(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private YaormMainController() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private YaormMainController(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.roylance.yaorm.YaormController.CommonAction.Builder subBuilder = null;
              if (getSchemas_ != null) {
                subBuilder = getSchemas_.toBuilder();
              }
              getSchemas_ = input.readMessage(org.roylance.yaorm.YaormController.CommonAction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(getSchemas_);
                getSchemas_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.roylance.yaorm.YaormController.CommonAction.Builder subBuilder = null;
              if (getTables_ != null) {
                subBuilder = getTables_.toBuilder();
              }
              getTables_ = input.readMessage(org.roylance.yaorm.YaormController.CommonAction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(getTables_);
                getTables_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              org.roylance.yaorm.YaormController.CommonAction.Builder subBuilder = null;
              if (getTableDefinition_ != null) {
                subBuilder = getTableDefinition_.toBuilder();
              }
              getTableDefinition_ = input.readMessage(org.roylance.yaorm.YaormController.CommonAction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(getTableDefinition_);
                getTableDefinition_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              org.roylance.yaorm.YaormController.CommonAction.Builder subBuilder = null;
              if (getTableDefinitions_ != null) {
                subBuilder = getTableDefinitions_.toBuilder();
              }
              getTableDefinitions_ = input.readMessage(org.roylance.yaorm.YaormController.CommonAction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(getTableDefinitions_);
                getTableDefinitions_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              org.roylance.yaorm.YaormController.CommonAction.Builder subBuilder = null;
              if (getRecordCount_ != null) {
                subBuilder = getRecordCount_.toBuilder();
              }
              getRecordCount_ = input.readMessage(org.roylance.yaorm.YaormController.CommonAction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(getRecordCount_);
                getRecordCount_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              org.roylance.yaorm.YaormController.CommonAction.Builder subBuilder = null;
              if (getRecords_ != null) {
                subBuilder = getRecords_.toBuilder();
              }
              getRecords_ = input.readMessage(org.roylance.yaorm.YaormController.CommonAction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(getRecords_);
                getRecords_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_YaormMainController_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_YaormMainController_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaorm.YaormController.YaormMainController.class, org.roylance.yaorm.YaormController.YaormMainController.Builder.class);
    }

    public static final int GET_SCHEMAS_FIELD_NUMBER = 1;
    private org.roylance.yaorm.YaormController.CommonAction getSchemas_;
    /**
     * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
     */
    public boolean hasGetSchemas() {
      return getSchemas_ != null;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
     */
    public org.roylance.yaorm.YaormController.CommonAction getGetSchemas() {
      return getSchemas_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getSchemas_;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
     */
    public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetSchemasOrBuilder() {
      return getGetSchemas();
    }

    public static final int GET_TABLES_FIELD_NUMBER = 2;
    private org.roylance.yaorm.YaormController.CommonAction getTables_;
    /**
     * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
     */
    public boolean hasGetTables() {
      return getTables_ != null;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
     */
    public org.roylance.yaorm.YaormController.CommonAction getGetTables() {
      return getTables_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTables_;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
     */
    public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTablesOrBuilder() {
      return getGetTables();
    }

    public static final int GET_TABLE_DEFINITION_FIELD_NUMBER = 3;
    private org.roylance.yaorm.YaormController.CommonAction getTableDefinition_;
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
     */
    public boolean hasGetTableDefinition() {
      return getTableDefinition_ != null;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
     */
    public org.roylance.yaorm.YaormController.CommonAction getGetTableDefinition() {
      return getTableDefinition_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTableDefinition_;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
     */
    public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTableDefinitionOrBuilder() {
      return getGetTableDefinition();
    }

    public static final int GET_TABLE_DEFINITIONS_FIELD_NUMBER = 4;
    private org.roylance.yaorm.YaormController.CommonAction getTableDefinitions_;
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
     */
    public boolean hasGetTableDefinitions() {
      return getTableDefinitions_ != null;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
     */
    public org.roylance.yaorm.YaormController.CommonAction getGetTableDefinitions() {
      return getTableDefinitions_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTableDefinitions_;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
     */
    public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTableDefinitionsOrBuilder() {
      return getGetTableDefinitions();
    }

    public static final int GET_RECORD_COUNT_FIELD_NUMBER = 5;
    private org.roylance.yaorm.YaormController.CommonAction getRecordCount_;
    /**
     * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
     */
    public boolean hasGetRecordCount() {
      return getRecordCount_ != null;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
     */
    public org.roylance.yaorm.YaormController.CommonAction getGetRecordCount() {
      return getRecordCount_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getRecordCount_;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
     */
    public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetRecordCountOrBuilder() {
      return getGetRecordCount();
    }

    public static final int GET_RECORDS_FIELD_NUMBER = 6;
    private org.roylance.yaorm.YaormController.CommonAction getRecords_;
    /**
     * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
     */
    public boolean hasGetRecords() {
      return getRecords_ != null;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
     */
    public org.roylance.yaorm.YaormController.CommonAction getGetRecords() {
      return getRecords_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getRecords_;
    }
    /**
     * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
     */
    public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetRecordsOrBuilder() {
      return getGetRecords();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (getSchemas_ != null) {
        output.writeMessage(1, getGetSchemas());
      }
      if (getTables_ != null) {
        output.writeMessage(2, getGetTables());
      }
      if (getTableDefinition_ != null) {
        output.writeMessage(3, getGetTableDefinition());
      }
      if (getTableDefinitions_ != null) {
        output.writeMessage(4, getGetTableDefinitions());
      }
      if (getRecordCount_ != null) {
        output.writeMessage(5, getGetRecordCount());
      }
      if (getRecords_ != null) {
        output.writeMessage(6, getGetRecords());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (getSchemas_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGetSchemas());
      }
      if (getTables_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGetTables());
      }
      if (getTableDefinition_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGetTableDefinition());
      }
      if (getTableDefinitions_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGetTableDefinitions());
      }
      if (getRecordCount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getGetRecordCount());
      }
      if (getRecords_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getGetRecords());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaorm.YaormController.YaormMainController)) {
        return super.equals(obj);
      }
      org.roylance.yaorm.YaormController.YaormMainController other = (org.roylance.yaorm.YaormController.YaormMainController) obj;

      boolean result = true;
      result = result && (hasGetSchemas() == other.hasGetSchemas());
      if (hasGetSchemas()) {
        result = result && getGetSchemas()
            .equals(other.getGetSchemas());
      }
      result = result && (hasGetTables() == other.hasGetTables());
      if (hasGetTables()) {
        result = result && getGetTables()
            .equals(other.getGetTables());
      }
      result = result && (hasGetTableDefinition() == other.hasGetTableDefinition());
      if (hasGetTableDefinition()) {
        result = result && getGetTableDefinition()
            .equals(other.getGetTableDefinition());
      }
      result = result && (hasGetTableDefinitions() == other.hasGetTableDefinitions());
      if (hasGetTableDefinitions()) {
        result = result && getGetTableDefinitions()
            .equals(other.getGetTableDefinitions());
      }
      result = result && (hasGetRecordCount() == other.hasGetRecordCount());
      if (hasGetRecordCount()) {
        result = result && getGetRecordCount()
            .equals(other.getGetRecordCount());
      }
      result = result && (hasGetRecords() == other.hasGetRecords());
      if (hasGetRecords()) {
        result = result && getGetRecords()
            .equals(other.getGetRecords());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGetSchemas()) {
        hash = (37 * hash) + GET_SCHEMAS_FIELD_NUMBER;
        hash = (53 * hash) + getGetSchemas().hashCode();
      }
      if (hasGetTables()) {
        hash = (37 * hash) + GET_TABLES_FIELD_NUMBER;
        hash = (53 * hash) + getGetTables().hashCode();
      }
      if (hasGetTableDefinition()) {
        hash = (37 * hash) + GET_TABLE_DEFINITION_FIELD_NUMBER;
        hash = (53 * hash) + getGetTableDefinition().hashCode();
      }
      if (hasGetTableDefinitions()) {
        hash = (37 * hash) + GET_TABLE_DEFINITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getGetTableDefinitions().hashCode();
      }
      if (hasGetRecordCount()) {
        hash = (37 * hash) + GET_RECORD_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getGetRecordCount().hashCode();
      }
      if (hasGetRecords()) {
        hash = (37 * hash) + GET_RECORDS_FIELD_NUMBER;
        hash = (53 * hash) + getGetRecords().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaorm.YaormController.YaormMainController parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaorm.YaormController.YaormMainController prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaorm.YaormMainController}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaorm.YaormMainController)
        org.roylance.yaorm.YaormController.YaormMainControllerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_YaormMainController_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_YaormMainController_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaorm.YaormController.YaormMainController.class, org.roylance.yaorm.YaormController.YaormMainController.Builder.class);
      }

      // Construct using org.roylance.yaorm.YaormController.YaormMainController.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (getSchemasBuilder_ == null) {
          getSchemas_ = null;
        } else {
          getSchemas_ = null;
          getSchemasBuilder_ = null;
        }
        if (getTablesBuilder_ == null) {
          getTables_ = null;
        } else {
          getTables_ = null;
          getTablesBuilder_ = null;
        }
        if (getTableDefinitionBuilder_ == null) {
          getTableDefinition_ = null;
        } else {
          getTableDefinition_ = null;
          getTableDefinitionBuilder_ = null;
        }
        if (getTableDefinitionsBuilder_ == null) {
          getTableDefinitions_ = null;
        } else {
          getTableDefinitions_ = null;
          getTableDefinitionsBuilder_ = null;
        }
        if (getRecordCountBuilder_ == null) {
          getRecordCount_ = null;
        } else {
          getRecordCount_ = null;
          getRecordCountBuilder_ = null;
        }
        if (getRecordsBuilder_ == null) {
          getRecords_ = null;
        } else {
          getRecords_ = null;
          getRecordsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaorm.YaormController.internal_static_org_roylance_yaorm_YaormMainController_descriptor;
      }

      @java.lang.Override
      public org.roylance.yaorm.YaormController.YaormMainController getDefaultInstanceForType() {
        return org.roylance.yaorm.YaormController.YaormMainController.getDefaultInstance();
      }

      @java.lang.Override
      public org.roylance.yaorm.YaormController.YaormMainController build() {
        org.roylance.yaorm.YaormController.YaormMainController result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.roylance.yaorm.YaormController.YaormMainController buildPartial() {
        org.roylance.yaorm.YaormController.YaormMainController result = new org.roylance.yaorm.YaormController.YaormMainController(this);
        if (getSchemasBuilder_ == null) {
          result.getSchemas_ = getSchemas_;
        } else {
          result.getSchemas_ = getSchemasBuilder_.build();
        }
        if (getTablesBuilder_ == null) {
          result.getTables_ = getTables_;
        } else {
          result.getTables_ = getTablesBuilder_.build();
        }
        if (getTableDefinitionBuilder_ == null) {
          result.getTableDefinition_ = getTableDefinition_;
        } else {
          result.getTableDefinition_ = getTableDefinitionBuilder_.build();
        }
        if (getTableDefinitionsBuilder_ == null) {
          result.getTableDefinitions_ = getTableDefinitions_;
        } else {
          result.getTableDefinitions_ = getTableDefinitionsBuilder_.build();
        }
        if (getRecordCountBuilder_ == null) {
          result.getRecordCount_ = getRecordCount_;
        } else {
          result.getRecordCount_ = getRecordCountBuilder_.build();
        }
        if (getRecordsBuilder_ == null) {
          result.getRecords_ = getRecords_;
        } else {
          result.getRecords_ = getRecordsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaorm.YaormController.YaormMainController) {
          return mergeFrom((org.roylance.yaorm.YaormController.YaormMainController)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaorm.YaormController.YaormMainController other) {
        if (other == org.roylance.yaorm.YaormController.YaormMainController.getDefaultInstance()) return this;
        if (other.hasGetSchemas()) {
          mergeGetSchemas(other.getGetSchemas());
        }
        if (other.hasGetTables()) {
          mergeGetTables(other.getGetTables());
        }
        if (other.hasGetTableDefinition()) {
          mergeGetTableDefinition(other.getGetTableDefinition());
        }
        if (other.hasGetTableDefinitions()) {
          mergeGetTableDefinitions(other.getGetTableDefinitions());
        }
        if (other.hasGetRecordCount()) {
          mergeGetRecordCount(other.getGetRecordCount());
        }
        if (other.hasGetRecords()) {
          mergeGetRecords(other.getGetRecords());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaorm.YaormController.YaormMainController parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaorm.YaormController.YaormMainController) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.roylance.yaorm.YaormController.CommonAction getSchemas_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> getSchemasBuilder_;
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      public boolean hasGetSchemas() {
        return getSchemasBuilder_ != null || getSchemas_ != null;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction getGetSchemas() {
        if (getSchemasBuilder_ == null) {
          return getSchemas_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getSchemas_;
        } else {
          return getSchemasBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      public Builder setGetSchemas(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getSchemasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          getSchemas_ = value;
          onChanged();
        } else {
          getSchemasBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      public Builder setGetSchemas(
          org.roylance.yaorm.YaormController.CommonAction.Builder builderForValue) {
        if (getSchemasBuilder_ == null) {
          getSchemas_ = builderForValue.build();
          onChanged();
        } else {
          getSchemasBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      public Builder mergeGetSchemas(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getSchemasBuilder_ == null) {
          if (getSchemas_ != null) {
            getSchemas_ =
              org.roylance.yaorm.YaormController.CommonAction.newBuilder(getSchemas_).mergeFrom(value).buildPartial();
          } else {
            getSchemas_ = value;
          }
          onChanged();
        } else {
          getSchemasBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      public Builder clearGetSchemas() {
        if (getSchemasBuilder_ == null) {
          getSchemas_ = null;
          onChanged();
        } else {
          getSchemas_ = null;
          getSchemasBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction.Builder getGetSchemasBuilder() {
        
        onChanged();
        return getGetSchemasFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetSchemasOrBuilder() {
        if (getSchemasBuilder_ != null) {
          return getSchemasBuilder_.getMessageOrBuilder();
        } else {
          return getSchemas_ == null ?
              org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getSchemas_;
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_schemas = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> 
          getGetSchemasFieldBuilder() {
        if (getSchemasBuilder_ == null) {
          getSchemasBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder>(
                  getGetSchemas(),
                  getParentForChildren(),
                  isClean());
          getSchemas_ = null;
        }
        return getSchemasBuilder_;
      }

      private org.roylance.yaorm.YaormController.CommonAction getTables_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> getTablesBuilder_;
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      public boolean hasGetTables() {
        return getTablesBuilder_ != null || getTables_ != null;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction getGetTables() {
        if (getTablesBuilder_ == null) {
          return getTables_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTables_;
        } else {
          return getTablesBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      public Builder setGetTables(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getTablesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          getTables_ = value;
          onChanged();
        } else {
          getTablesBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      public Builder setGetTables(
          org.roylance.yaorm.YaormController.CommonAction.Builder builderForValue) {
        if (getTablesBuilder_ == null) {
          getTables_ = builderForValue.build();
          onChanged();
        } else {
          getTablesBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      public Builder mergeGetTables(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getTablesBuilder_ == null) {
          if (getTables_ != null) {
            getTables_ =
              org.roylance.yaorm.YaormController.CommonAction.newBuilder(getTables_).mergeFrom(value).buildPartial();
          } else {
            getTables_ = value;
          }
          onChanged();
        } else {
          getTablesBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      public Builder clearGetTables() {
        if (getTablesBuilder_ == null) {
          getTables_ = null;
          onChanged();
        } else {
          getTables_ = null;
          getTablesBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction.Builder getGetTablesBuilder() {
        
        onChanged();
        return getGetTablesFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTablesOrBuilder() {
        if (getTablesBuilder_ != null) {
          return getTablesBuilder_.getMessageOrBuilder();
        } else {
          return getTables_ == null ?
              org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTables_;
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_tables = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> 
          getGetTablesFieldBuilder() {
        if (getTablesBuilder_ == null) {
          getTablesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder>(
                  getGetTables(),
                  getParentForChildren(),
                  isClean());
          getTables_ = null;
        }
        return getTablesBuilder_;
      }

      private org.roylance.yaorm.YaormController.CommonAction getTableDefinition_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> getTableDefinitionBuilder_;
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      public boolean hasGetTableDefinition() {
        return getTableDefinitionBuilder_ != null || getTableDefinition_ != null;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction getGetTableDefinition() {
        if (getTableDefinitionBuilder_ == null) {
          return getTableDefinition_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTableDefinition_;
        } else {
          return getTableDefinitionBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      public Builder setGetTableDefinition(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getTableDefinitionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          getTableDefinition_ = value;
          onChanged();
        } else {
          getTableDefinitionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      public Builder setGetTableDefinition(
          org.roylance.yaorm.YaormController.CommonAction.Builder builderForValue) {
        if (getTableDefinitionBuilder_ == null) {
          getTableDefinition_ = builderForValue.build();
          onChanged();
        } else {
          getTableDefinitionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      public Builder mergeGetTableDefinition(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getTableDefinitionBuilder_ == null) {
          if (getTableDefinition_ != null) {
            getTableDefinition_ =
              org.roylance.yaorm.YaormController.CommonAction.newBuilder(getTableDefinition_).mergeFrom(value).buildPartial();
          } else {
            getTableDefinition_ = value;
          }
          onChanged();
        } else {
          getTableDefinitionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      public Builder clearGetTableDefinition() {
        if (getTableDefinitionBuilder_ == null) {
          getTableDefinition_ = null;
          onChanged();
        } else {
          getTableDefinition_ = null;
          getTableDefinitionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction.Builder getGetTableDefinitionBuilder() {
        
        onChanged();
        return getGetTableDefinitionFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTableDefinitionOrBuilder() {
        if (getTableDefinitionBuilder_ != null) {
          return getTableDefinitionBuilder_.getMessageOrBuilder();
        } else {
          return getTableDefinition_ == null ?
              org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTableDefinition_;
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definition = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> 
          getGetTableDefinitionFieldBuilder() {
        if (getTableDefinitionBuilder_ == null) {
          getTableDefinitionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder>(
                  getGetTableDefinition(),
                  getParentForChildren(),
                  isClean());
          getTableDefinition_ = null;
        }
        return getTableDefinitionBuilder_;
      }

      private org.roylance.yaorm.YaormController.CommonAction getTableDefinitions_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> getTableDefinitionsBuilder_;
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      public boolean hasGetTableDefinitions() {
        return getTableDefinitionsBuilder_ != null || getTableDefinitions_ != null;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction getGetTableDefinitions() {
        if (getTableDefinitionsBuilder_ == null) {
          return getTableDefinitions_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTableDefinitions_;
        } else {
          return getTableDefinitionsBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      public Builder setGetTableDefinitions(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getTableDefinitionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          getTableDefinitions_ = value;
          onChanged();
        } else {
          getTableDefinitionsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      public Builder setGetTableDefinitions(
          org.roylance.yaorm.YaormController.CommonAction.Builder builderForValue) {
        if (getTableDefinitionsBuilder_ == null) {
          getTableDefinitions_ = builderForValue.build();
          onChanged();
        } else {
          getTableDefinitionsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      public Builder mergeGetTableDefinitions(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getTableDefinitionsBuilder_ == null) {
          if (getTableDefinitions_ != null) {
            getTableDefinitions_ =
              org.roylance.yaorm.YaormController.CommonAction.newBuilder(getTableDefinitions_).mergeFrom(value).buildPartial();
          } else {
            getTableDefinitions_ = value;
          }
          onChanged();
        } else {
          getTableDefinitionsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      public Builder clearGetTableDefinitions() {
        if (getTableDefinitionsBuilder_ == null) {
          getTableDefinitions_ = null;
          onChanged();
        } else {
          getTableDefinitions_ = null;
          getTableDefinitionsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction.Builder getGetTableDefinitionsBuilder() {
        
        onChanged();
        return getGetTableDefinitionsFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetTableDefinitionsOrBuilder() {
        if (getTableDefinitionsBuilder_ != null) {
          return getTableDefinitionsBuilder_.getMessageOrBuilder();
        } else {
          return getTableDefinitions_ == null ?
              org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getTableDefinitions_;
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_table_definitions = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> 
          getGetTableDefinitionsFieldBuilder() {
        if (getTableDefinitionsBuilder_ == null) {
          getTableDefinitionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder>(
                  getGetTableDefinitions(),
                  getParentForChildren(),
                  isClean());
          getTableDefinitions_ = null;
        }
        return getTableDefinitionsBuilder_;
      }

      private org.roylance.yaorm.YaormController.CommonAction getRecordCount_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> getRecordCountBuilder_;
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      public boolean hasGetRecordCount() {
        return getRecordCountBuilder_ != null || getRecordCount_ != null;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction getGetRecordCount() {
        if (getRecordCountBuilder_ == null) {
          return getRecordCount_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getRecordCount_;
        } else {
          return getRecordCountBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      public Builder setGetRecordCount(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getRecordCountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          getRecordCount_ = value;
          onChanged();
        } else {
          getRecordCountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      public Builder setGetRecordCount(
          org.roylance.yaorm.YaormController.CommonAction.Builder builderForValue) {
        if (getRecordCountBuilder_ == null) {
          getRecordCount_ = builderForValue.build();
          onChanged();
        } else {
          getRecordCountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      public Builder mergeGetRecordCount(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getRecordCountBuilder_ == null) {
          if (getRecordCount_ != null) {
            getRecordCount_ =
              org.roylance.yaorm.YaormController.CommonAction.newBuilder(getRecordCount_).mergeFrom(value).buildPartial();
          } else {
            getRecordCount_ = value;
          }
          onChanged();
        } else {
          getRecordCountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      public Builder clearGetRecordCount() {
        if (getRecordCountBuilder_ == null) {
          getRecordCount_ = null;
          onChanged();
        } else {
          getRecordCount_ = null;
          getRecordCountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction.Builder getGetRecordCountBuilder() {
        
        onChanged();
        return getGetRecordCountFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetRecordCountOrBuilder() {
        if (getRecordCountBuilder_ != null) {
          return getRecordCountBuilder_.getMessageOrBuilder();
        } else {
          return getRecordCount_ == null ?
              org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getRecordCount_;
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_record_count = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> 
          getGetRecordCountFieldBuilder() {
        if (getRecordCountBuilder_ == null) {
          getRecordCountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder>(
                  getGetRecordCount(),
                  getParentForChildren(),
                  isClean());
          getRecordCount_ = null;
        }
        return getRecordCountBuilder_;
      }

      private org.roylance.yaorm.YaormController.CommonAction getRecords_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> getRecordsBuilder_;
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      public boolean hasGetRecords() {
        return getRecordsBuilder_ != null || getRecords_ != null;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction getGetRecords() {
        if (getRecordsBuilder_ == null) {
          return getRecords_ == null ? org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getRecords_;
        } else {
          return getRecordsBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      public Builder setGetRecords(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getRecordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          getRecords_ = value;
          onChanged();
        } else {
          getRecordsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      public Builder setGetRecords(
          org.roylance.yaorm.YaormController.CommonAction.Builder builderForValue) {
        if (getRecordsBuilder_ == null) {
          getRecords_ = builderForValue.build();
          onChanged();
        } else {
          getRecordsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      public Builder mergeGetRecords(org.roylance.yaorm.YaormController.CommonAction value) {
        if (getRecordsBuilder_ == null) {
          if (getRecords_ != null) {
            getRecords_ =
              org.roylance.yaorm.YaormController.CommonAction.newBuilder(getRecords_).mergeFrom(value).buildPartial();
          } else {
            getRecords_ = value;
          }
          onChanged();
        } else {
          getRecordsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      public Builder clearGetRecords() {
        if (getRecordsBuilder_ == null) {
          getRecords_ = null;
          onChanged();
        } else {
          getRecords_ = null;
          getRecordsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      public org.roylance.yaorm.YaormController.CommonAction.Builder getGetRecordsBuilder() {
        
        onChanged();
        return getGetRecordsFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      public org.roylance.yaorm.YaormController.CommonActionOrBuilder getGetRecordsOrBuilder() {
        if (getRecordsBuilder_ != null) {
          return getRecordsBuilder_.getMessageOrBuilder();
        } else {
          return getRecords_ == null ?
              org.roylance.yaorm.YaormController.CommonAction.getDefaultInstance() : getRecords_;
        }
      }
      /**
       * <code>.org.roylance.yaorm.CommonAction get_records = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder> 
          getGetRecordsFieldBuilder() {
        if (getRecordsBuilder_ == null) {
          getRecordsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaorm.YaormController.CommonAction, org.roylance.yaorm.YaormController.CommonAction.Builder, org.roylance.yaorm.YaormController.CommonActionOrBuilder>(
                  getGetRecords(),
                  getParentForChildren(),
                  isClean());
          getRecords_ = null;
        }
        return getRecordsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaorm.YaormMainController)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaorm.YaormMainController)
    private static final org.roylance.yaorm.YaormController.YaormMainController DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaorm.YaormController.YaormMainController();
    }

    public static org.roylance.yaorm.YaormController.YaormMainController getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<YaormMainController>
        PARSER = new com.google.protobuf.AbstractParser<YaormMainController>() {
      @java.lang.Override
      public YaormMainController parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new YaormMainController(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<YaormMainController> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<YaormMainController> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.roylance.yaorm.YaormController.YaormMainController getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaorm_CommonAction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaorm_CommonAction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaorm_YaormMainController_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaorm_YaormMainController_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026yaorm_controller.proto\022\022org.roylance.y" +
      "aorm\032\021yaorm_model.proto\"z\n\014CommonAction\022" +
      "3\n\007request\030\001 \001(\0132\".org.roylance.yaorm.UI" +
      "YaormRequest\0225\n\010response\030\002 \001(\0132#.org.roy" +
      "lance.yaorm.UIYaormResponse\"\366\002\n\023YaormMai" +
      "nController\0225\n\013get_schemas\030\001 \001(\0132 .org.r" +
      "oylance.yaorm.CommonAction\0224\n\nget_tables" +
      "\030\002 \001(\0132 .org.roylance.yaorm.CommonAction" +
      "\022>\n\024get_table_definition\030\003 \001(\0132 .org.roy" +
      "lance.yaorm.CommonAction\022?\n\025get_table_de" +
      "finitions\030\004 \001(\0132 .org.roylance.yaorm.Com" +
      "monAction\022:\n\020get_record_count\030\005 \001(\0132 .or" +
      "g.roylance.yaorm.CommonAction\0225\n\013get_rec" +
      "ords\030\006 \001(\0132 .org.roylance.yaorm.CommonAc" +
      "tionb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.roylance.yaorm.YaormModel.getDescriptor(),
        }, assigner);
    internal_static_org_roylance_yaorm_CommonAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_roylance_yaorm_CommonAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaorm_CommonAction_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_org_roylance_yaorm_YaormMainController_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_roylance_yaorm_YaormMainController_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaorm_YaormMainController_descriptor,
        new java.lang.String[] { "GetSchemas", "GetTables", "GetTableDefinition", "GetTableDefinitions", "GetRecordCount", "GetRecords", });
    org.roylance.yaorm.YaormModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
