# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yaorm_controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import yaorm_model_pb2 as yaorm__model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yaorm_controller.proto',
  package='org.roylance.yaorm',
  syntax='proto3',
  serialized_pb=_b('\n\x16yaorm_controller.proto\x12\x12org.roylance.yaorm\x1a\x11yaorm_model.proto\"z\n\x0c\x43ommonAction\x12\x33\n\x07request\x18\x01 \x01(\x0b\x32\".org.roylance.yaorm.UIYaormRequest\x12\x35\n\x08response\x18\x02 \x01(\x0b\x32#.org.roylance.yaorm.UIYaormResponse\"\xf6\x02\n\x13YaormMainController\x12\x35\n\x0bget_schemas\x18\x01 \x01(\x0b\x32 .org.roylance.yaorm.CommonAction\x12\x34\n\nget_tables\x18\x02 \x01(\x0b\x32 .org.roylance.yaorm.CommonAction\x12>\n\x14get_table_definition\x18\x03 \x01(\x0b\x32 .org.roylance.yaorm.CommonAction\x12?\n\x15get_table_definitions\x18\x04 \x01(\x0b\x32 .org.roylance.yaorm.CommonAction\x12:\n\x10get_record_count\x18\x05 \x01(\x0b\x32 .org.roylance.yaorm.CommonAction\x12\x35\n\x0bget_records\x18\x06 \x01(\x0b\x32 .org.roylance.yaorm.CommonActionb\x06proto3')
  ,
  dependencies=[yaorm__model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMONACTION = _descriptor.Descriptor(
  name='CommonAction',
  full_name='org.roylance.yaorm.CommonAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='org.roylance.yaorm.CommonAction.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='org.roylance.yaorm.CommonAction.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=187,
)


_YAORMMAINCONTROLLER = _descriptor.Descriptor(
  name='YaormMainController',
  full_name='org.roylance.yaorm.YaormMainController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_schemas', full_name='org.roylance.yaorm.YaormMainController.get_schemas', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_tables', full_name='org.roylance.yaorm.YaormMainController.get_tables', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_table_definition', full_name='org.roylance.yaorm.YaormMainController.get_table_definition', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_table_definitions', full_name='org.roylance.yaorm.YaormMainController.get_table_definitions', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_record_count', full_name='org.roylance.yaorm.YaormMainController.get_record_count', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_records', full_name='org.roylance.yaorm.YaormMainController.get_records', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=564,
)

_COMMONACTION.fields_by_name['request'].message_type = yaorm__model__pb2._UIYAORMREQUEST
_COMMONACTION.fields_by_name['response'].message_type = yaorm__model__pb2._UIYAORMRESPONSE
_YAORMMAINCONTROLLER.fields_by_name['get_schemas'].message_type = _COMMONACTION
_YAORMMAINCONTROLLER.fields_by_name['get_tables'].message_type = _COMMONACTION
_YAORMMAINCONTROLLER.fields_by_name['get_table_definition'].message_type = _COMMONACTION
_YAORMMAINCONTROLLER.fields_by_name['get_table_definitions'].message_type = _COMMONACTION
_YAORMMAINCONTROLLER.fields_by_name['get_record_count'].message_type = _COMMONACTION
_YAORMMAINCONTROLLER.fields_by_name['get_records'].message_type = _COMMONACTION
DESCRIPTOR.message_types_by_name['CommonAction'] = _COMMONACTION
DESCRIPTOR.message_types_by_name['YaormMainController'] = _YAORMMAINCONTROLLER

CommonAction = _reflection.GeneratedProtocolMessageType('CommonAction', (_message.Message,), dict(
  DESCRIPTOR = _COMMONACTION,
  __module__ = 'yaorm_controller_pb2'
  # @@protoc_insertion_point(class_scope:org.roylance.yaorm.CommonAction)
  ))
_sym_db.RegisterMessage(CommonAction)

YaormMainController = _reflection.GeneratedProtocolMessageType('YaormMainController', (_message.Message,), dict(
  DESCRIPTOR = _YAORMMAINCONTROLLER,
  __module__ = 'yaorm_controller_pb2'
  # @@protoc_insertion_point(class_scope:org.roylance.yaorm.YaormMainController)
  ))
_sym_db.RegisterMessage(YaormMainController)


# @@protoc_insertion_point(module_scope)
