// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestModel.proto

package org.roylance.yaorm;

public final class TestModel {
  private TestModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SimpleInsertTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaorm.SimpleInsertTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string display = 2;</code>
     */
    java.lang.String getDisplay();
    /**
     * <code>optional string display = 2;</code>
     */
    com.google.protobuf.ByteString
        getDisplayBytes();

    /**
     * <code>optional int32 test_int32 = 3;</code>
     */
    int getTestInt32();

    /**
     * <code>optional int64 test_int64 = 4;</code>
     */
    long getTestInt64();

    /**
     * <code>optional uint32 test_uint32 = 5;</code>
     */
    int getTestUint32();

    /**
     * <code>optional uint64 test_uint64 = 6;</code>
     */
    long getTestUint64();

    /**
     * <code>optional sint32 test_sint32 = 7;</code>
     */
    int getTestSint32();

    /**
     * <code>optional sint64 test_sint64 = 8;</code>
     */
    long getTestSint64();

    /**
     * <code>optional fixed32 test_fixed32 = 9;</code>
     */
    int getTestFixed32();

    /**
     * <code>optional fixed64 test_fixed64 = 10;</code>
     */
    long getTestFixed64();

    /**
     * <code>optional sfixed32 test_sfixed32 = 11;</code>
     */
    int getTestSfixed32();

    /**
     * <code>optional sfixed64 test_sfixed64 = 12;</code>
     */
    long getTestSfixed64();

    /**
     * <code>optional bool test_bool = 13;</code>
     */
    boolean getTestBool();

    /**
     * <code>optional bytes test_bytes = 14;</code>
     */
    com.google.protobuf.ByteString getTestBytes();

    /**
     * <code>optional double test_double = 15;</code>
     */
    double getTestDouble();

    /**
     * <code>optional float test_float = 16;</code>
     */
    float getTestFloat();

    /**
     * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
     */
    int getCoolTypeValue();
    /**
     * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
     */
    org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType getCoolType();

    /**
     * <code>optional .org.roylance.yaorm.Child child = 18;</code>
     */
    boolean hasChild();
    /**
     * <code>optional .org.roylance.yaorm.Child child = 18;</code>
     */
    org.roylance.yaorm.TestModel.Child getChild();
    /**
     * <code>optional .org.roylance.yaorm.Child child = 18;</code>
     */
    org.roylance.yaorm.TestModel.ChildOrBuilder getChildOrBuilder();

    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    java.util.List<org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType> getCoolTypesList();
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    int getCoolTypesCount();
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType getCoolTypes(int index);
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    java.util.List<java.lang.Integer>
    getCoolTypesValueList();
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    int getCoolTypesValue(int index);

    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    java.util.List<org.roylance.yaorm.TestModel.Child> 
        getChildsList();
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    org.roylance.yaorm.TestModel.Child getChilds(int index);
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    int getChildsCount();
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    java.util.List<? extends org.roylance.yaorm.TestModel.ChildOrBuilder> 
        getChildsOrBuilderList();
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    org.roylance.yaorm.TestModel.ChildOrBuilder getChildsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.roylance.yaorm.SimpleInsertTest}
   */
  public  static final class SimpleInsertTest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaorm.SimpleInsertTest)
      SimpleInsertTestOrBuilder {
    // Use SimpleInsertTest.newBuilder() to construct.
    private SimpleInsertTest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SimpleInsertTest() {
      id_ = "";
      display_ = "";
      testInt32_ = 0;
      testInt64_ = 0L;
      testUint32_ = 0;
      testUint64_ = 0L;
      testSint32_ = 0;
      testSint64_ = 0L;
      testFixed32_ = 0;
      testFixed64_ = 0L;
      testSfixed32_ = 0;
      testSfixed64_ = 0L;
      testBool_ = false;
      testBytes_ = com.google.protobuf.ByteString.EMPTY;
      testDouble_ = 0D;
      testFloat_ = 0F;
      coolType_ = 0;
      coolTypes_ = java.util.Collections.emptyList();
      childs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SimpleInsertTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              display_ = s;
              break;
            }
            case 24: {

              testInt32_ = input.readInt32();
              break;
            }
            case 32: {

              testInt64_ = input.readInt64();
              break;
            }
            case 40: {

              testUint32_ = input.readUInt32();
              break;
            }
            case 48: {

              testUint64_ = input.readUInt64();
              break;
            }
            case 56: {

              testSint32_ = input.readSInt32();
              break;
            }
            case 64: {

              testSint64_ = input.readSInt64();
              break;
            }
            case 77: {

              testFixed32_ = input.readFixed32();
              break;
            }
            case 81: {

              testFixed64_ = input.readFixed64();
              break;
            }
            case 93: {

              testSfixed32_ = input.readSFixed32();
              break;
            }
            case 97: {

              testSfixed64_ = input.readSFixed64();
              break;
            }
            case 104: {

              testBool_ = input.readBool();
              break;
            }
            case 114: {

              testBytes_ = input.readBytes();
              break;
            }
            case 121: {

              testDouble_ = input.readDouble();
              break;
            }
            case 133: {

              testFloat_ = input.readFloat();
              break;
            }
            case 136: {
              int rawValue = input.readEnum();

              coolType_ = rawValue;
              break;
            }
            case 146: {
              org.roylance.yaorm.TestModel.Child.Builder subBuilder = null;
              if (child_ != null) {
                subBuilder = child_.toBuilder();
              }
              child_ = input.readMessage(org.roylance.yaorm.TestModel.Child.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(child_);
                child_ = subBuilder.buildPartial();
              }

              break;
            }
            case 152: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00040000) == 0x00040000)) {
                coolTypes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00040000;
              }
              coolTypes_.add(rawValue);
              break;
            }
            case 154: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00040000) == 0x00040000)) {
                  coolTypes_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00040000;
                }
                coolTypes_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            case 162: {
              if (!((mutable_bitField0_ & 0x00080000) == 0x00080000)) {
                childs_ = new java.util.ArrayList<org.roylance.yaorm.TestModel.Child>();
                mutable_bitField0_ |= 0x00080000;
              }
              childs_.add(input.readMessage(org.roylance.yaorm.TestModel.Child.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00040000) == 0x00040000)) {
          coolTypes_ = java.util.Collections.unmodifiableList(coolTypes_);
        }
        if (((mutable_bitField0_ & 0x00080000) == 0x00080000)) {
          childs_ = java.util.Collections.unmodifiableList(childs_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_SimpleInsertTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_SimpleInsertTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaorm.TestModel.SimpleInsertTest.class, org.roylance.yaorm.TestModel.SimpleInsertTest.Builder.class);
    }

    /**
     * Protobuf enum {@code org.roylance.yaorm.SimpleInsertTest.CoolType}
     */
    public enum CoolType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEST = 0;</code>
       */
      TEST(0, 0),
      /**
       * <code>SAMPLE = 1;</code>
       */
      SAMPLE(1, 1),
      /**
       * <code>SURPRISED = 2;</code>
       */
      SURPRISED(2, 2),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>TEST = 0;</code>
       */
      public static final int TEST_VALUE = 0;
      /**
       * <code>SAMPLE = 1;</code>
       */
      public static final int SAMPLE_VALUE = 1;
      /**
       * <code>SURPRISED = 2;</code>
       */
      public static final int SURPRISED_VALUE = 2;


      public final int getNumber() {
        if (index == -1) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      public static CoolType valueOf(int value) {
        switch (value) {
          case 0: return TEST;
          case 1: return SAMPLE;
          case 2: return SURPRISED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CoolType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CoolType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CoolType>() {
              public CoolType findValueByNumber(int number) {
                return CoolType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.roylance.yaorm.TestModel.SimpleInsertTest.getDescriptor().getEnumTypes().get(0);
      }

      private static final CoolType[] VALUES = values();

      public static CoolType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CoolType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.roylance.yaorm.SimpleInsertTest.CoolType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPLAY_FIELD_NUMBER = 2;
    private volatile java.lang.Object display_;
    /**
     * <code>optional string display = 2;</code>
     */
    public java.lang.String getDisplay() {
      java.lang.Object ref = display_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        display_ = s;
        return s;
      }
    }
    /**
     * <code>optional string display = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayBytes() {
      java.lang.Object ref = display_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        display_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST_INT32_FIELD_NUMBER = 3;
    private int testInt32_;
    /**
     * <code>optional int32 test_int32 = 3;</code>
     */
    public int getTestInt32() {
      return testInt32_;
    }

    public static final int TEST_INT64_FIELD_NUMBER = 4;
    private long testInt64_;
    /**
     * <code>optional int64 test_int64 = 4;</code>
     */
    public long getTestInt64() {
      return testInt64_;
    }

    public static final int TEST_UINT32_FIELD_NUMBER = 5;
    private int testUint32_;
    /**
     * <code>optional uint32 test_uint32 = 5;</code>
     */
    public int getTestUint32() {
      return testUint32_;
    }

    public static final int TEST_UINT64_FIELD_NUMBER = 6;
    private long testUint64_;
    /**
     * <code>optional uint64 test_uint64 = 6;</code>
     */
    public long getTestUint64() {
      return testUint64_;
    }

    public static final int TEST_SINT32_FIELD_NUMBER = 7;
    private int testSint32_;
    /**
     * <code>optional sint32 test_sint32 = 7;</code>
     */
    public int getTestSint32() {
      return testSint32_;
    }

    public static final int TEST_SINT64_FIELD_NUMBER = 8;
    private long testSint64_;
    /**
     * <code>optional sint64 test_sint64 = 8;</code>
     */
    public long getTestSint64() {
      return testSint64_;
    }

    public static final int TEST_FIXED32_FIELD_NUMBER = 9;
    private int testFixed32_;
    /**
     * <code>optional fixed32 test_fixed32 = 9;</code>
     */
    public int getTestFixed32() {
      return testFixed32_;
    }

    public static final int TEST_FIXED64_FIELD_NUMBER = 10;
    private long testFixed64_;
    /**
     * <code>optional fixed64 test_fixed64 = 10;</code>
     */
    public long getTestFixed64() {
      return testFixed64_;
    }

    public static final int TEST_SFIXED32_FIELD_NUMBER = 11;
    private int testSfixed32_;
    /**
     * <code>optional sfixed32 test_sfixed32 = 11;</code>
     */
    public int getTestSfixed32() {
      return testSfixed32_;
    }

    public static final int TEST_SFIXED64_FIELD_NUMBER = 12;
    private long testSfixed64_;
    /**
     * <code>optional sfixed64 test_sfixed64 = 12;</code>
     */
    public long getTestSfixed64() {
      return testSfixed64_;
    }

    public static final int TEST_BOOL_FIELD_NUMBER = 13;
    private boolean testBool_;
    /**
     * <code>optional bool test_bool = 13;</code>
     */
    public boolean getTestBool() {
      return testBool_;
    }

    public static final int TEST_BYTES_FIELD_NUMBER = 14;
    private com.google.protobuf.ByteString testBytes_;
    /**
     * <code>optional bytes test_bytes = 14;</code>
     */
    public com.google.protobuf.ByteString getTestBytes() {
      return testBytes_;
    }

    public static final int TEST_DOUBLE_FIELD_NUMBER = 15;
    private double testDouble_;
    /**
     * <code>optional double test_double = 15;</code>
     */
    public double getTestDouble() {
      return testDouble_;
    }

    public static final int TEST_FLOAT_FIELD_NUMBER = 16;
    private float testFloat_;
    /**
     * <code>optional float test_float = 16;</code>
     */
    public float getTestFloat() {
      return testFloat_;
    }

    public static final int COOL_TYPE_FIELD_NUMBER = 17;
    private int coolType_;
    /**
     * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
     */
    public int getCoolTypeValue() {
      return coolType_;
    }
    /**
     * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
     */
    public org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType getCoolType() {
      org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType result = org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType.valueOf(coolType_);
      return result == null ? org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType.UNRECOGNIZED : result;
    }

    public static final int CHILD_FIELD_NUMBER = 18;
    private org.roylance.yaorm.TestModel.Child child_;
    /**
     * <code>optional .org.roylance.yaorm.Child child = 18;</code>
     */
    public boolean hasChild() {
      return child_ != null;
    }
    /**
     * <code>optional .org.roylance.yaorm.Child child = 18;</code>
     */
    public org.roylance.yaorm.TestModel.Child getChild() {
      return child_ == null ? org.roylance.yaorm.TestModel.Child.getDefaultInstance() : child_;
    }
    /**
     * <code>optional .org.roylance.yaorm.Child child = 18;</code>
     */
    public org.roylance.yaorm.TestModel.ChildOrBuilder getChildOrBuilder() {
      return getChild();
    }

    public static final int COOL_TYPES_FIELD_NUMBER = 19;
    private java.util.List<java.lang.Integer> coolTypes_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType> coolTypes_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType>() {
              public org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType convert(java.lang.Integer from) {
                org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType result = org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType.valueOf(from);
                return result == null ? org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    public java.util.List<org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType> getCoolTypesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType>(coolTypes_, coolTypes_converter_);
    }
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    public int getCoolTypesCount() {
      return coolTypes_.size();
    }
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    public org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType getCoolTypes(int index) {
      return coolTypes_converter_.convert(coolTypes_.get(index));
    }
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    public java.util.List<java.lang.Integer>
    getCoolTypesValueList() {
      return coolTypes_;
    }
    /**
     * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
     */
    public int getCoolTypesValue(int index) {
      return coolTypes_.get(index);
    }
    private int coolTypesMemoizedSerializedSize;

    public static final int CHILDS_FIELD_NUMBER = 20;
    private java.util.List<org.roylance.yaorm.TestModel.Child> childs_;
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    public java.util.List<org.roylance.yaorm.TestModel.Child> getChildsList() {
      return childs_;
    }
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    public java.util.List<? extends org.roylance.yaorm.TestModel.ChildOrBuilder> 
        getChildsOrBuilderList() {
      return childs_;
    }
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    public int getChildsCount() {
      return childs_.size();
    }
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    public org.roylance.yaorm.TestModel.Child getChilds(int index) {
      return childs_.get(index);
    }
    /**
     * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
     */
    public org.roylance.yaorm.TestModel.ChildOrBuilder getChildsOrBuilder(
        int index) {
      return childs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!getDisplayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, display_);
      }
      if (testInt32_ != 0) {
        output.writeInt32(3, testInt32_);
      }
      if (testInt64_ != 0L) {
        output.writeInt64(4, testInt64_);
      }
      if (testUint32_ != 0) {
        output.writeUInt32(5, testUint32_);
      }
      if (testUint64_ != 0L) {
        output.writeUInt64(6, testUint64_);
      }
      if (testSint32_ != 0) {
        output.writeSInt32(7, testSint32_);
      }
      if (testSint64_ != 0L) {
        output.writeSInt64(8, testSint64_);
      }
      if (testFixed32_ != 0) {
        output.writeFixed32(9, testFixed32_);
      }
      if (testFixed64_ != 0L) {
        output.writeFixed64(10, testFixed64_);
      }
      if (testSfixed32_ != 0) {
        output.writeSFixed32(11, testSfixed32_);
      }
      if (testSfixed64_ != 0L) {
        output.writeSFixed64(12, testSfixed64_);
      }
      if (testBool_ != false) {
        output.writeBool(13, testBool_);
      }
      if (!testBytes_.isEmpty()) {
        output.writeBytes(14, testBytes_);
      }
      if (testDouble_ != 0D) {
        output.writeDouble(15, testDouble_);
      }
      if (testFloat_ != 0F) {
        output.writeFloat(16, testFloat_);
      }
      if (coolType_ != org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType.TEST.getNumber()) {
        output.writeEnum(17, coolType_);
      }
      if (child_ != null) {
        output.writeMessage(18, getChild());
      }
      if (getCoolTypesList().size() > 0) {
        output.writeRawVarint32(154);
        output.writeRawVarint32(coolTypesMemoizedSerializedSize);
      }
      for (int i = 0; i < coolTypes_.size(); i++) {
        output.writeEnumNoTag(coolTypes_.get(i));
      }
      for (int i = 0; i < childs_.size(); i++) {
        output.writeMessage(20, childs_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!getDisplayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, display_);
      }
      if (testInt32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, testInt32_);
      }
      if (testInt64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, testInt64_);
      }
      if (testUint32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, testUint32_);
      }
      if (testUint64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, testUint64_);
      }
      if (testSint32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, testSint32_);
      }
      if (testSint64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(8, testSint64_);
      }
      if (testFixed32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(9, testFixed32_);
      }
      if (testFixed64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(10, testFixed64_);
      }
      if (testSfixed32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(11, testSfixed32_);
      }
      if (testSfixed64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(12, testSfixed64_);
      }
      if (testBool_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, testBool_);
      }
      if (!testBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, testBytes_);
      }
      if (testDouble_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(15, testDouble_);
      }
      if (testFloat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(16, testFloat_);
      }
      if (coolType_ != org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType.TEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(17, coolType_);
      }
      if (child_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(18, getChild());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < coolTypes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(coolTypes_.get(i));
        }
        size += dataSize;
        if (!getCoolTypesList().isEmpty()) {  size += 2;
          size += com.google.protobuf.CodedOutputStream
            .computeRawVarint32Size(dataSize);
        }coolTypesMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < childs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, childs_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.roylance.yaorm.TestModel.SimpleInsertTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaorm.TestModel.SimpleInsertTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaorm.SimpleInsertTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaorm.SimpleInsertTest)
        org.roylance.yaorm.TestModel.SimpleInsertTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_SimpleInsertTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_SimpleInsertTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaorm.TestModel.SimpleInsertTest.class, org.roylance.yaorm.TestModel.SimpleInsertTest.Builder.class);
      }

      // Construct using org.roylance.yaorm.TestModel.SimpleInsertTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChildsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        display_ = "";

        testInt32_ = 0;

        testInt64_ = 0L;

        testUint32_ = 0;

        testUint64_ = 0L;

        testSint32_ = 0;

        testSint64_ = 0L;

        testFixed32_ = 0;

        testFixed64_ = 0L;

        testSfixed32_ = 0;

        testSfixed64_ = 0L;

        testBool_ = false;

        testBytes_ = com.google.protobuf.ByteString.EMPTY;

        testDouble_ = 0D;

        testFloat_ = 0F;

        coolType_ = 0;

        if (childBuilder_ == null) {
          child_ = null;
        } else {
          child_ = null;
          childBuilder_ = null;
        }
        coolTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00040000);
        if (childsBuilder_ == null) {
          childs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00080000);
        } else {
          childsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_SimpleInsertTest_descriptor;
      }

      public org.roylance.yaorm.TestModel.SimpleInsertTest getDefaultInstanceForType() {
        return org.roylance.yaorm.TestModel.SimpleInsertTest.getDefaultInstance();
      }

      public org.roylance.yaorm.TestModel.SimpleInsertTest build() {
        org.roylance.yaorm.TestModel.SimpleInsertTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaorm.TestModel.SimpleInsertTest buildPartial() {
        org.roylance.yaorm.TestModel.SimpleInsertTest result = new org.roylance.yaorm.TestModel.SimpleInsertTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.display_ = display_;
        result.testInt32_ = testInt32_;
        result.testInt64_ = testInt64_;
        result.testUint32_ = testUint32_;
        result.testUint64_ = testUint64_;
        result.testSint32_ = testSint32_;
        result.testSint64_ = testSint64_;
        result.testFixed32_ = testFixed32_;
        result.testFixed64_ = testFixed64_;
        result.testSfixed32_ = testSfixed32_;
        result.testSfixed64_ = testSfixed64_;
        result.testBool_ = testBool_;
        result.testBytes_ = testBytes_;
        result.testDouble_ = testDouble_;
        result.testFloat_ = testFloat_;
        result.coolType_ = coolType_;
        if (childBuilder_ == null) {
          result.child_ = child_;
        } else {
          result.child_ = childBuilder_.build();
        }
        if (((bitField0_ & 0x00040000) == 0x00040000)) {
          coolTypes_ = java.util.Collections.unmodifiableList(coolTypes_);
          bitField0_ = (bitField0_ & ~0x00040000);
        }
        result.coolTypes_ = coolTypes_;
        if (childsBuilder_ == null) {
          if (((bitField0_ & 0x00080000) == 0x00080000)) {
            childs_ = java.util.Collections.unmodifiableList(childs_);
            bitField0_ = (bitField0_ & ~0x00080000);
          }
          result.childs_ = childs_;
        } else {
          result.childs_ = childsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaorm.TestModel.SimpleInsertTest) {
          return mergeFrom((org.roylance.yaorm.TestModel.SimpleInsertTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaorm.TestModel.SimpleInsertTest other) {
        if (other == org.roylance.yaorm.TestModel.SimpleInsertTest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getDisplay().isEmpty()) {
          display_ = other.display_;
          onChanged();
        }
        if (other.getTestInt32() != 0) {
          setTestInt32(other.getTestInt32());
        }
        if (other.getTestInt64() != 0L) {
          setTestInt64(other.getTestInt64());
        }
        if (other.getTestUint32() != 0) {
          setTestUint32(other.getTestUint32());
        }
        if (other.getTestUint64() != 0L) {
          setTestUint64(other.getTestUint64());
        }
        if (other.getTestSint32() != 0) {
          setTestSint32(other.getTestSint32());
        }
        if (other.getTestSint64() != 0L) {
          setTestSint64(other.getTestSint64());
        }
        if (other.getTestFixed32() != 0) {
          setTestFixed32(other.getTestFixed32());
        }
        if (other.getTestFixed64() != 0L) {
          setTestFixed64(other.getTestFixed64());
        }
        if (other.getTestSfixed32() != 0) {
          setTestSfixed32(other.getTestSfixed32());
        }
        if (other.getTestSfixed64() != 0L) {
          setTestSfixed64(other.getTestSfixed64());
        }
        if (other.getTestBool() != false) {
          setTestBool(other.getTestBool());
        }
        if (other.getTestBytes() != com.google.protobuf.ByteString.EMPTY) {
          setTestBytes(other.getTestBytes());
        }
        if (other.getTestDouble() != 0D) {
          setTestDouble(other.getTestDouble());
        }
        if (other.getTestFloat() != 0F) {
          setTestFloat(other.getTestFloat());
        }
        if (other.coolType_ != 0) {
          setCoolTypeValue(other.getCoolTypeValue());
        }
        if (other.hasChild()) {
          mergeChild(other.getChild());
        }
        if (!other.coolTypes_.isEmpty()) {
          if (coolTypes_.isEmpty()) {
            coolTypes_ = other.coolTypes_;
            bitField0_ = (bitField0_ & ~0x00040000);
          } else {
            ensureCoolTypesIsMutable();
            coolTypes_.addAll(other.coolTypes_);
          }
          onChanged();
        }
        if (childsBuilder_ == null) {
          if (!other.childs_.isEmpty()) {
            if (childs_.isEmpty()) {
              childs_ = other.childs_;
              bitField0_ = (bitField0_ & ~0x00080000);
            } else {
              ensureChildsIsMutable();
              childs_.addAll(other.childs_);
            }
            onChanged();
          }
        } else {
          if (!other.childs_.isEmpty()) {
            if (childsBuilder_.isEmpty()) {
              childsBuilder_.dispose();
              childsBuilder_ = null;
              childs_ = other.childs_;
              bitField0_ = (bitField0_ & ~0x00080000);
              childsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChildsFieldBuilder() : null;
            } else {
              childsBuilder_.addAllMessages(other.childs_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaorm.TestModel.SimpleInsertTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaorm.TestModel.SimpleInsertTest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object display_ = "";
      /**
       * <code>optional string display = 2;</code>
       */
      public java.lang.String getDisplay() {
        java.lang.Object ref = display_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          display_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string display = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDisplayBytes() {
        java.lang.Object ref = display_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          display_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string display = 2;</code>
       */
      public Builder setDisplay(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        display_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string display = 2;</code>
       */
      public Builder clearDisplay() {
        
        display_ = getDefaultInstance().getDisplay();
        onChanged();
        return this;
      }
      /**
       * <code>optional string display = 2;</code>
       */
      public Builder setDisplayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        display_ = value;
        onChanged();
        return this;
      }

      private int testInt32_ ;
      /**
       * <code>optional int32 test_int32 = 3;</code>
       */
      public int getTestInt32() {
        return testInt32_;
      }
      /**
       * <code>optional int32 test_int32 = 3;</code>
       */
      public Builder setTestInt32(int value) {
        
        testInt32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 test_int32 = 3;</code>
       */
      public Builder clearTestInt32() {
        
        testInt32_ = 0;
        onChanged();
        return this;
      }

      private long testInt64_ ;
      /**
       * <code>optional int64 test_int64 = 4;</code>
       */
      public long getTestInt64() {
        return testInt64_;
      }
      /**
       * <code>optional int64 test_int64 = 4;</code>
       */
      public Builder setTestInt64(long value) {
        
        testInt64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 test_int64 = 4;</code>
       */
      public Builder clearTestInt64() {
        
        testInt64_ = 0L;
        onChanged();
        return this;
      }

      private int testUint32_ ;
      /**
       * <code>optional uint32 test_uint32 = 5;</code>
       */
      public int getTestUint32() {
        return testUint32_;
      }
      /**
       * <code>optional uint32 test_uint32 = 5;</code>
       */
      public Builder setTestUint32(int value) {
        
        testUint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 test_uint32 = 5;</code>
       */
      public Builder clearTestUint32() {
        
        testUint32_ = 0;
        onChanged();
        return this;
      }

      private long testUint64_ ;
      /**
       * <code>optional uint64 test_uint64 = 6;</code>
       */
      public long getTestUint64() {
        return testUint64_;
      }
      /**
       * <code>optional uint64 test_uint64 = 6;</code>
       */
      public Builder setTestUint64(long value) {
        
        testUint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 test_uint64 = 6;</code>
       */
      public Builder clearTestUint64() {
        
        testUint64_ = 0L;
        onChanged();
        return this;
      }

      private int testSint32_ ;
      /**
       * <code>optional sint32 test_sint32 = 7;</code>
       */
      public int getTestSint32() {
        return testSint32_;
      }
      /**
       * <code>optional sint32 test_sint32 = 7;</code>
       */
      public Builder setTestSint32(int value) {
        
        testSint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 test_sint32 = 7;</code>
       */
      public Builder clearTestSint32() {
        
        testSint32_ = 0;
        onChanged();
        return this;
      }

      private long testSint64_ ;
      /**
       * <code>optional sint64 test_sint64 = 8;</code>
       */
      public long getTestSint64() {
        return testSint64_;
      }
      /**
       * <code>optional sint64 test_sint64 = 8;</code>
       */
      public Builder setTestSint64(long value) {
        
        testSint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 test_sint64 = 8;</code>
       */
      public Builder clearTestSint64() {
        
        testSint64_ = 0L;
        onChanged();
        return this;
      }

      private int testFixed32_ ;
      /**
       * <code>optional fixed32 test_fixed32 = 9;</code>
       */
      public int getTestFixed32() {
        return testFixed32_;
      }
      /**
       * <code>optional fixed32 test_fixed32 = 9;</code>
       */
      public Builder setTestFixed32(int value) {
        
        testFixed32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 test_fixed32 = 9;</code>
       */
      public Builder clearTestFixed32() {
        
        testFixed32_ = 0;
        onChanged();
        return this;
      }

      private long testFixed64_ ;
      /**
       * <code>optional fixed64 test_fixed64 = 10;</code>
       */
      public long getTestFixed64() {
        return testFixed64_;
      }
      /**
       * <code>optional fixed64 test_fixed64 = 10;</code>
       */
      public Builder setTestFixed64(long value) {
        
        testFixed64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 test_fixed64 = 10;</code>
       */
      public Builder clearTestFixed64() {
        
        testFixed64_ = 0L;
        onChanged();
        return this;
      }

      private int testSfixed32_ ;
      /**
       * <code>optional sfixed32 test_sfixed32 = 11;</code>
       */
      public int getTestSfixed32() {
        return testSfixed32_;
      }
      /**
       * <code>optional sfixed32 test_sfixed32 = 11;</code>
       */
      public Builder setTestSfixed32(int value) {
        
        testSfixed32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed32 test_sfixed32 = 11;</code>
       */
      public Builder clearTestSfixed32() {
        
        testSfixed32_ = 0;
        onChanged();
        return this;
      }

      private long testSfixed64_ ;
      /**
       * <code>optional sfixed64 test_sfixed64 = 12;</code>
       */
      public long getTestSfixed64() {
        return testSfixed64_;
      }
      /**
       * <code>optional sfixed64 test_sfixed64 = 12;</code>
       */
      public Builder setTestSfixed64(long value) {
        
        testSfixed64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed64 test_sfixed64 = 12;</code>
       */
      public Builder clearTestSfixed64() {
        
        testSfixed64_ = 0L;
        onChanged();
        return this;
      }

      private boolean testBool_ ;
      /**
       * <code>optional bool test_bool = 13;</code>
       */
      public boolean getTestBool() {
        return testBool_;
      }
      /**
       * <code>optional bool test_bool = 13;</code>
       */
      public Builder setTestBool(boolean value) {
        
        testBool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool test_bool = 13;</code>
       */
      public Builder clearTestBool() {
        
        testBool_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString testBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes test_bytes = 14;</code>
       */
      public com.google.protobuf.ByteString getTestBytes() {
        return testBytes_;
      }
      /**
       * <code>optional bytes test_bytes = 14;</code>
       */
      public Builder setTestBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        testBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes test_bytes = 14;</code>
       */
      public Builder clearTestBytes() {
        
        testBytes_ = getDefaultInstance().getTestBytes();
        onChanged();
        return this;
      }

      private double testDouble_ ;
      /**
       * <code>optional double test_double = 15;</code>
       */
      public double getTestDouble() {
        return testDouble_;
      }
      /**
       * <code>optional double test_double = 15;</code>
       */
      public Builder setTestDouble(double value) {
        
        testDouble_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double test_double = 15;</code>
       */
      public Builder clearTestDouble() {
        
        testDouble_ = 0D;
        onChanged();
        return this;
      }

      private float testFloat_ ;
      /**
       * <code>optional float test_float = 16;</code>
       */
      public float getTestFloat() {
        return testFloat_;
      }
      /**
       * <code>optional float test_float = 16;</code>
       */
      public Builder setTestFloat(float value) {
        
        testFloat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float test_float = 16;</code>
       */
      public Builder clearTestFloat() {
        
        testFloat_ = 0F;
        onChanged();
        return this;
      }

      private int coolType_ = 0;
      /**
       * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
       */
      public int getCoolTypeValue() {
        return coolType_;
      }
      /**
       * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
       */
      public Builder setCoolTypeValue(int value) {
        coolType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
       */
      public org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType getCoolType() {
        org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType result = org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType.valueOf(coolType_);
        return result == null ? org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
       */
      public Builder setCoolType(org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        coolType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.roylance.yaorm.SimpleInsertTest.CoolType cool_type = 17;</code>
       */
      public Builder clearCoolType() {
        
        coolType_ = 0;
        onChanged();
        return this;
      }

      private org.roylance.yaorm.TestModel.Child child_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yaorm.TestModel.Child, org.roylance.yaorm.TestModel.Child.Builder, org.roylance.yaorm.TestModel.ChildOrBuilder> childBuilder_;
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      public boolean hasChild() {
        return childBuilder_ != null || child_ != null;
      }
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      public org.roylance.yaorm.TestModel.Child getChild() {
        if (childBuilder_ == null) {
          return child_ == null ? org.roylance.yaorm.TestModel.Child.getDefaultInstance() : child_;
        } else {
          return childBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      public Builder setChild(org.roylance.yaorm.TestModel.Child value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          child_ = value;
          onChanged();
        } else {
          childBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      public Builder setChild(
          org.roylance.yaorm.TestModel.Child.Builder builderForValue) {
        if (childBuilder_ == null) {
          child_ = builderForValue.build();
          onChanged();
        } else {
          childBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      public Builder mergeChild(org.roylance.yaorm.TestModel.Child value) {
        if (childBuilder_ == null) {
          if (child_ != null) {
            child_ =
              org.roylance.yaorm.TestModel.Child.newBuilder(child_).mergeFrom(value).buildPartial();
          } else {
            child_ = value;
          }
          onChanged();
        } else {
          childBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      public Builder clearChild() {
        if (childBuilder_ == null) {
          child_ = null;
          onChanged();
        } else {
          child_ = null;
          childBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      public org.roylance.yaorm.TestModel.Child.Builder getChildBuilder() {
        
        onChanged();
        return getChildFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      public org.roylance.yaorm.TestModel.ChildOrBuilder getChildOrBuilder() {
        if (childBuilder_ != null) {
          return childBuilder_.getMessageOrBuilder();
        } else {
          return child_ == null ?
              org.roylance.yaorm.TestModel.Child.getDefaultInstance() : child_;
        }
      }
      /**
       * <code>optional .org.roylance.yaorm.Child child = 18;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yaorm.TestModel.Child, org.roylance.yaorm.TestModel.Child.Builder, org.roylance.yaorm.TestModel.ChildOrBuilder> 
          getChildFieldBuilder() {
        if (childBuilder_ == null) {
          childBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.roylance.yaorm.TestModel.Child, org.roylance.yaorm.TestModel.Child.Builder, org.roylance.yaorm.TestModel.ChildOrBuilder>(
                  getChild(),
                  getParentForChildren(),
                  isClean());
          child_ = null;
        }
        return childBuilder_;
      }

      private java.util.List<java.lang.Integer> coolTypes_ =
        java.util.Collections.emptyList();
      private void ensureCoolTypesIsMutable() {
        if (!((bitField0_ & 0x00040000) == 0x00040000)) {
          coolTypes_ = new java.util.ArrayList<java.lang.Integer>(coolTypes_);
          bitField0_ |= 0x00040000;
        }
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public java.util.List<org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType> getCoolTypesList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType>(coolTypes_, coolTypes_converter_);
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public int getCoolTypesCount() {
        return coolTypes_.size();
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType getCoolTypes(int index) {
        return coolTypes_converter_.convert(coolTypes_.get(index));
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public Builder setCoolTypes(
          int index, org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoolTypesIsMutable();
        coolTypes_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public Builder addCoolTypes(org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoolTypesIsMutable();
        coolTypes_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public Builder addAllCoolTypes(
          java.lang.Iterable<? extends org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType> values) {
        ensureCoolTypesIsMutable();
        for (org.roylance.yaorm.TestModel.SimpleInsertTest.CoolType value : values) {
          coolTypes_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public Builder clearCoolTypes() {
        coolTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00040000);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public java.util.List<java.lang.Integer>
      getCoolTypesValueList() {
        return java.util.Collections.unmodifiableList(coolTypes_);
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public int getCoolTypesValue(int index) {
        return coolTypes_.get(index);
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public Builder setCoolTypesValue(
          int index, int value) {
        ensureCoolTypesIsMutable();
        coolTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public Builder addCoolTypesValue(int value) {
        ensureCoolTypesIsMutable();
        coolTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.SimpleInsertTest.CoolType cool_types = 19;</code>
       */
      public Builder addAllCoolTypesValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureCoolTypesIsMutable();
        for (int value : values) {
          coolTypes_.add(value);
        }
        onChanged();
        return this;
      }

      private java.util.List<org.roylance.yaorm.TestModel.Child> childs_ =
        java.util.Collections.emptyList();
      private void ensureChildsIsMutable() {
        if (!((bitField0_ & 0x00080000) == 0x00080000)) {
          childs_ = new java.util.ArrayList<org.roylance.yaorm.TestModel.Child>(childs_);
          bitField0_ |= 0x00080000;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.roylance.yaorm.TestModel.Child, org.roylance.yaorm.TestModel.Child.Builder, org.roylance.yaorm.TestModel.ChildOrBuilder> childsBuilder_;

      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public java.util.List<org.roylance.yaorm.TestModel.Child> getChildsList() {
        if (childsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(childs_);
        } else {
          return childsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public int getChildsCount() {
        if (childsBuilder_ == null) {
          return childs_.size();
        } else {
          return childsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public org.roylance.yaorm.TestModel.Child getChilds(int index) {
        if (childsBuilder_ == null) {
          return childs_.get(index);
        } else {
          return childsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder setChilds(
          int index, org.roylance.yaorm.TestModel.Child value) {
        if (childsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildsIsMutable();
          childs_.set(index, value);
          onChanged();
        } else {
          childsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder setChilds(
          int index, org.roylance.yaorm.TestModel.Child.Builder builderForValue) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          childs_.set(index, builderForValue.build());
          onChanged();
        } else {
          childsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder addChilds(org.roylance.yaorm.TestModel.Child value) {
        if (childsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildsIsMutable();
          childs_.add(value);
          onChanged();
        } else {
          childsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder addChilds(
          int index, org.roylance.yaorm.TestModel.Child value) {
        if (childsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildsIsMutable();
          childs_.add(index, value);
          onChanged();
        } else {
          childsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder addChilds(
          org.roylance.yaorm.TestModel.Child.Builder builderForValue) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          childs_.add(builderForValue.build());
          onChanged();
        } else {
          childsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder addChilds(
          int index, org.roylance.yaorm.TestModel.Child.Builder builderForValue) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          childs_.add(index, builderForValue.build());
          onChanged();
        } else {
          childsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder addAllChilds(
          java.lang.Iterable<? extends org.roylance.yaorm.TestModel.Child> values) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, childs_);
          onChanged();
        } else {
          childsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder clearChilds() {
        if (childsBuilder_ == null) {
          childs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00080000);
          onChanged();
        } else {
          childsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public Builder removeChilds(int index) {
        if (childsBuilder_ == null) {
          ensureChildsIsMutable();
          childs_.remove(index);
          onChanged();
        } else {
          childsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public org.roylance.yaorm.TestModel.Child.Builder getChildsBuilder(
          int index) {
        return getChildsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public org.roylance.yaorm.TestModel.ChildOrBuilder getChildsOrBuilder(
          int index) {
        if (childsBuilder_ == null) {
          return childs_.get(index);  } else {
          return childsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public java.util.List<? extends org.roylance.yaorm.TestModel.ChildOrBuilder> 
           getChildsOrBuilderList() {
        if (childsBuilder_ != null) {
          return childsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(childs_);
        }
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public org.roylance.yaorm.TestModel.Child.Builder addChildsBuilder() {
        return getChildsFieldBuilder().addBuilder(
            org.roylance.yaorm.TestModel.Child.getDefaultInstance());
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public org.roylance.yaorm.TestModel.Child.Builder addChildsBuilder(
          int index) {
        return getChildsFieldBuilder().addBuilder(
            index, org.roylance.yaorm.TestModel.Child.getDefaultInstance());
      }
      /**
       * <code>repeated .org.roylance.yaorm.Child childs = 20;</code>
       */
      public java.util.List<org.roylance.yaorm.TestModel.Child.Builder> 
           getChildsBuilderList() {
        return getChildsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.roylance.yaorm.TestModel.Child, org.roylance.yaorm.TestModel.Child.Builder, org.roylance.yaorm.TestModel.ChildOrBuilder> 
          getChildsFieldBuilder() {
        if (childsBuilder_ == null) {
          childsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.roylance.yaorm.TestModel.Child, org.roylance.yaorm.TestModel.Child.Builder, org.roylance.yaorm.TestModel.ChildOrBuilder>(
                  childs_,
                  ((bitField0_ & 0x00080000) == 0x00080000),
                  getParentForChildren(),
                  isClean());
          childs_ = null;
        }
        return childsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaorm.SimpleInsertTest)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaorm.SimpleInsertTest)
    private static final org.roylance.yaorm.TestModel.SimpleInsertTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaorm.TestModel.SimpleInsertTest();
    }

    public static org.roylance.yaorm.TestModel.SimpleInsertTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleInsertTest>
        PARSER = new com.google.protobuf.AbstractParser<SimpleInsertTest>() {
      public SimpleInsertTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SimpleInsertTest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<SimpleInsertTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleInsertTest> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaorm.TestModel.SimpleInsertTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChildOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaorm.Child)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string test_display = 2;</code>
     */
    java.lang.String getTestDisplay();
    /**
     * <code>optional string test_display = 2;</code>
     */
    com.google.protobuf.ByteString
        getTestDisplayBytes();
  }
  /**
   * Protobuf type {@code org.roylance.yaorm.Child}
   */
  public  static final class Child extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaorm.Child)
      ChildOrBuilder {
    // Use Child.newBuilder() to construct.
    private Child(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Child() {
      id_ = "";
      testDisplay_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Child(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              testDisplay_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_Child_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_Child_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaorm.TestModel.Child.class, org.roylance.yaorm.TestModel.Child.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST_DISPLAY_FIELD_NUMBER = 2;
    private volatile java.lang.Object testDisplay_;
    /**
     * <code>optional string test_display = 2;</code>
     */
    public java.lang.String getTestDisplay() {
      java.lang.Object ref = testDisplay_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testDisplay_ = s;
        return s;
      }
    }
    /**
     * <code>optional string test_display = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTestDisplayBytes() {
      java.lang.Object ref = testDisplay_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testDisplay_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!getTestDisplayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, testDisplay_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!getTestDisplayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, testDisplay_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.roylance.yaorm.TestModel.Child parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.TestModel.Child parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.TestModel.Child parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaorm.TestModel.Child parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaorm.TestModel.Child parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.roylance.yaorm.TestModel.Child parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.roylance.yaorm.TestModel.Child parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.roylance.yaorm.TestModel.Child parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.roylance.yaorm.TestModel.Child parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.roylance.yaorm.TestModel.Child parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaorm.TestModel.Child prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaorm.Child}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaorm.Child)
        org.roylance.yaorm.TestModel.ChildOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_Child_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_Child_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaorm.TestModel.Child.class, org.roylance.yaorm.TestModel.Child.Builder.class);
      }

      // Construct using org.roylance.yaorm.TestModel.Child.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        testDisplay_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaorm.TestModel.internal_static_org_roylance_yaorm_Child_descriptor;
      }

      public org.roylance.yaorm.TestModel.Child getDefaultInstanceForType() {
        return org.roylance.yaorm.TestModel.Child.getDefaultInstance();
      }

      public org.roylance.yaorm.TestModel.Child build() {
        org.roylance.yaorm.TestModel.Child result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaorm.TestModel.Child buildPartial() {
        org.roylance.yaorm.TestModel.Child result = new org.roylance.yaorm.TestModel.Child(this);
        result.id_ = id_;
        result.testDisplay_ = testDisplay_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaorm.TestModel.Child) {
          return mergeFrom((org.roylance.yaorm.TestModel.Child)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaorm.TestModel.Child other) {
        if (other == org.roylance.yaorm.TestModel.Child.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getTestDisplay().isEmpty()) {
          testDisplay_ = other.testDisplay_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaorm.TestModel.Child parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaorm.TestModel.Child) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object testDisplay_ = "";
      /**
       * <code>optional string test_display = 2;</code>
       */
      public java.lang.String getTestDisplay() {
        java.lang.Object ref = testDisplay_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          testDisplay_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string test_display = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTestDisplayBytes() {
        java.lang.Object ref = testDisplay_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          testDisplay_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string test_display = 2;</code>
       */
      public Builder setTestDisplay(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        testDisplay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string test_display = 2;</code>
       */
      public Builder clearTestDisplay() {
        
        testDisplay_ = getDefaultInstance().getTestDisplay();
        onChanged();
        return this;
      }
      /**
       * <code>optional string test_display = 2;</code>
       */
      public Builder setTestDisplayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        testDisplay_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaorm.Child)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaorm.Child)
    private static final org.roylance.yaorm.TestModel.Child DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaorm.TestModel.Child();
    }

    public static org.roylance.yaorm.TestModel.Child getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Child>
        PARSER = new com.google.protobuf.AbstractParser<Child>() {
      public Child parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Child(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Child> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Child> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaorm.TestModel.Child getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaorm_SimpleInsertTest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_roylance_yaorm_SimpleInsertTest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaorm_Child_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_roylance_yaorm_Child_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017TestModel.proto\022\022org.roylance.yaorm\"\340\004" +
      "\n\020SimpleInsertTest\022\n\n\002id\030\001 \001(\t\022\017\n\007displa" +
      "y\030\002 \001(\t\022\022\n\ntest_int32\030\003 \001(\005\022\022\n\ntest_int6" +
      "4\030\004 \001(\003\022\023\n\013test_uint32\030\005 \001(\r\022\023\n\013test_uin" +
      "t64\030\006 \001(\004\022\023\n\013test_sint32\030\007 \001(\021\022\023\n\013test_s" +
      "int64\030\010 \001(\022\022\024\n\014test_fixed32\030\t \001(\007\022\024\n\014tes" +
      "t_fixed64\030\n \001(\006\022\025\n\rtest_sfixed32\030\013 \001(\017\022\025" +
      "\n\rtest_sfixed64\030\014 \001(\020\022\021\n\ttest_bool\030\r \001(\010" +
      "\022\022\n\ntest_bytes\030\016 \001(\014\022\023\n\013test_double\030\017 \001(" +
      "\001\022\022\n\ntest_float\030\020 \001(\002\022@\n\tcool_type\030\021 \001(\016",
      "2-.org.roylance.yaorm.SimpleInsertTest.C" +
      "oolType\022(\n\005child\030\022 \001(\0132\031.org.roylance.ya" +
      "orm.Child\022A\n\ncool_types\030\023 \003(\0162-.org.royl" +
      "ance.yaorm.SimpleInsertTest.CoolType\022)\n\006" +
      "childs\030\024 \003(\0132\031.org.roylance.yaorm.Child\"" +
      "/\n\010CoolType\022\010\n\004TEST\020\000\022\n\n\006SAMPLE\020\001\022\r\n\tSUR" +
      "PRISED\020\002\")\n\005Child\022\n\n\002id\030\001 \001(\t\022\024\n\014test_di" +
      "splay\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_roylance_yaorm_SimpleInsertTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_roylance_yaorm_SimpleInsertTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_roylance_yaorm_SimpleInsertTest_descriptor,
        new java.lang.String[] { "Id", "Display", "TestInt32", "TestInt64", "TestUint32", "TestUint64", "TestSint32", "TestSint64", "TestFixed32", "TestFixed64", "TestSfixed32", "TestSfixed64", "TestBool", "TestBytes", "TestDouble", "TestFloat", "CoolType", "Child", "CoolTypes", "Childs", });
    internal_static_org_roylance_yaorm_Child_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_roylance_yaorm_Child_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_roylance_yaorm_Child_descriptor,
        new java.lang.String[] { "Id", "TestDisplay", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
