/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_roylance_yaorm_services_YaormMainJNIBridge */

#ifndef _Included_org_roylance_yaorm_services_YaormMainJNIBridge
#define _Included_org_roylance_yaorm_services_YaormMainJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_roylance_yaorm_services_YaormMainJNIBridge
 * Method:    get_schemasJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaorm_services_YaormMainJNIBridge_get_1schemasJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaorm_services_YaormMainJNIBridge
 * Method:    get_tablesJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaorm_services_YaormMainJNIBridge_get_1tablesJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaorm_services_YaormMainJNIBridge
 * Method:    get_table_definitionJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaorm_services_YaormMainJNIBridge_get_1table_1definitionJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaorm_services_YaormMainJNIBridge
 * Method:    get_table_definitionsJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaorm_services_YaormMainJNIBridge_get_1table_1definitionsJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaorm_services_YaormMainJNIBridge
 * Method:    get_record_countJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaorm_services_YaormMainJNIBridge_get_1record_1countJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaorm_services_YaormMainJNIBridge
 * Method:    get_recordsJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaorm_services_YaormMainJNIBridge_get_1recordsJNI
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
