// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yaorm_controller.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Roylance.Yaorm {

  /// <summary>Holder for reflection information generated from yaorm_controller.proto</summary>
  public static partial class YaormControllerReflection {

    #region Descriptor
    /// <summary>File descriptor for yaorm_controller.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static YaormControllerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZ5YW9ybV9jb250cm9sbGVyLnByb3RvEhJvcmcucm95bGFuY2UueWFvcm0a",
            "EXlhb3JtX21vZGVsLnByb3RvInoKDENvbW1vbkFjdGlvbhIzCgdyZXF1ZXN0",
            "GAEgASgLMiIub3JnLnJveWxhbmNlLnlhb3JtLlVJWWFvcm1SZXF1ZXN0EjUK",
            "CHJlc3BvbnNlGAIgASgLMiMub3JnLnJveWxhbmNlLnlhb3JtLlVJWWFvcm1S",
            "ZXNwb25zZSL2AgoTWWFvcm1NYWluQ29udHJvbGxlchI1CgtnZXRfc2NoZW1h",
            "cxgBIAEoCzIgLm9yZy5yb3lsYW5jZS55YW9ybS5Db21tb25BY3Rpb24SNAoK",
            "Z2V0X3RhYmxlcxgCIAEoCzIgLm9yZy5yb3lsYW5jZS55YW9ybS5Db21tb25B",
            "Y3Rpb24SPgoUZ2V0X3RhYmxlX2RlZmluaXRpb24YAyABKAsyIC5vcmcucm95",
            "bGFuY2UueWFvcm0uQ29tbW9uQWN0aW9uEj8KFWdldF90YWJsZV9kZWZpbml0",
            "aW9ucxgEIAEoCzIgLm9yZy5yb3lsYW5jZS55YW9ybS5Db21tb25BY3Rpb24S",
            "OgoQZ2V0X3JlY29yZF9jb3VudBgFIAEoCzIgLm9yZy5yb3lsYW5jZS55YW9y",
            "bS5Db21tb25BY3Rpb24SNQoLZ2V0X3JlY29yZHMYBiABKAsyIC5vcmcucm95",
            "bGFuY2UueWFvcm0uQ29tbW9uQWN0aW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Org.Roylance.Yaorm.YaormModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Roylance.Yaorm.CommonAction), global::Org.Roylance.Yaorm.CommonAction.Parser, new[]{ "Request", "Response" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Roylance.Yaorm.YaormMainController), global::Org.Roylance.Yaorm.YaormMainController.Parser, new[]{ "GetSchemas", "GetTables", "GetTableDefinition", "GetTableDefinitions", "GetRecordCount", "GetRecords" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CommonAction : pb::IMessage<CommonAction> {
    private static readonly pb::MessageParser<CommonAction> _parser = new pb::MessageParser<CommonAction>(() => new CommonAction());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommonAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Roylance.Yaorm.YaormControllerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonAction(CommonAction other) : this() {
      Request = other.request_ != null ? other.Request.Clone() : null;
      Response = other.response_ != null ? other.Response.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonAction Clone() {
      return new CommonAction(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private global::Org.Roylance.Yaorm.UIYaormRequest request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yaorm.UIYaormRequest Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 2;
    private global::Org.Roylance.Yaorm.UIYaormResponse response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yaorm.UIYaormResponse Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommonAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommonAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Request, other.Request)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (request_ != null) hash ^= Request.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommonAction other) {
      if (other == null) {
        return;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          request_ = new global::Org.Roylance.Yaorm.UIYaormRequest();
        }
        Request.MergeFrom(other.Request);
      }
      if (other.response_ != null) {
        if (response_ == null) {
          response_ = new global::Org.Roylance.Yaorm.UIYaormResponse();
        }
        Response.MergeFrom(other.Response);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (request_ == null) {
              request_ = new global::Org.Roylance.Yaorm.UIYaormRequest();
            }
            input.ReadMessage(request_);
            break;
          }
          case 18: {
            if (response_ == null) {
              response_ = new global::Org.Roylance.Yaorm.UIYaormResponse();
            }
            input.ReadMessage(response_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class YaormMainController : pb::IMessage<YaormMainController> {
    private static readonly pb::MessageParser<YaormMainController> _parser = new pb::MessageParser<YaormMainController>(() => new YaormMainController());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<YaormMainController> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Roylance.Yaorm.YaormControllerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public YaormMainController() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public YaormMainController(YaormMainController other) : this() {
      GetSchemas = other.getSchemas_ != null ? other.GetSchemas.Clone() : null;
      GetTables = other.getTables_ != null ? other.GetTables.Clone() : null;
      GetTableDefinition = other.getTableDefinition_ != null ? other.GetTableDefinition.Clone() : null;
      GetTableDefinitions = other.getTableDefinitions_ != null ? other.GetTableDefinitions.Clone() : null;
      GetRecordCount = other.getRecordCount_ != null ? other.GetRecordCount.Clone() : null;
      GetRecords = other.getRecords_ != null ? other.GetRecords.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public YaormMainController Clone() {
      return new YaormMainController(this);
    }

    /// <summary>Field number for the "get_schemas" field.</summary>
    public const int GetSchemasFieldNumber = 1;
    private global::Org.Roylance.Yaorm.CommonAction getSchemas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yaorm.CommonAction GetSchemas {
      get { return getSchemas_; }
      set {
        getSchemas_ = value;
      }
    }

    /// <summary>Field number for the "get_tables" field.</summary>
    public const int GetTablesFieldNumber = 2;
    private global::Org.Roylance.Yaorm.CommonAction getTables_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yaorm.CommonAction GetTables {
      get { return getTables_; }
      set {
        getTables_ = value;
      }
    }

    /// <summary>Field number for the "get_table_definition" field.</summary>
    public const int GetTableDefinitionFieldNumber = 3;
    private global::Org.Roylance.Yaorm.CommonAction getTableDefinition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yaorm.CommonAction GetTableDefinition {
      get { return getTableDefinition_; }
      set {
        getTableDefinition_ = value;
      }
    }

    /// <summary>Field number for the "get_table_definitions" field.</summary>
    public const int GetTableDefinitionsFieldNumber = 4;
    private global::Org.Roylance.Yaorm.CommonAction getTableDefinitions_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yaorm.CommonAction GetTableDefinitions {
      get { return getTableDefinitions_; }
      set {
        getTableDefinitions_ = value;
      }
    }

    /// <summary>Field number for the "get_record_count" field.</summary>
    public const int GetRecordCountFieldNumber = 5;
    private global::Org.Roylance.Yaorm.CommonAction getRecordCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yaorm.CommonAction GetRecordCount {
      get { return getRecordCount_; }
      set {
        getRecordCount_ = value;
      }
    }

    /// <summary>Field number for the "get_records" field.</summary>
    public const int GetRecordsFieldNumber = 6;
    private global::Org.Roylance.Yaorm.CommonAction getRecords_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yaorm.CommonAction GetRecords {
      get { return getRecords_; }
      set {
        getRecords_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as YaormMainController);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(YaormMainController other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(GetSchemas, other.GetSchemas)) return false;
      if (!object.Equals(GetTables, other.GetTables)) return false;
      if (!object.Equals(GetTableDefinition, other.GetTableDefinition)) return false;
      if (!object.Equals(GetTableDefinitions, other.GetTableDefinitions)) return false;
      if (!object.Equals(GetRecordCount, other.GetRecordCount)) return false;
      if (!object.Equals(GetRecords, other.GetRecords)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (getSchemas_ != null) hash ^= GetSchemas.GetHashCode();
      if (getTables_ != null) hash ^= GetTables.GetHashCode();
      if (getTableDefinition_ != null) hash ^= GetTableDefinition.GetHashCode();
      if (getTableDefinitions_ != null) hash ^= GetTableDefinitions.GetHashCode();
      if (getRecordCount_ != null) hash ^= GetRecordCount.GetHashCode();
      if (getRecords_ != null) hash ^= GetRecords.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (getSchemas_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(GetSchemas);
      }
      if (getTables_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GetTables);
      }
      if (getTableDefinition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GetTableDefinition);
      }
      if (getTableDefinitions_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(GetTableDefinitions);
      }
      if (getRecordCount_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(GetRecordCount);
      }
      if (getRecords_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(GetRecords);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (getSchemas_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetSchemas);
      }
      if (getTables_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetTables);
      }
      if (getTableDefinition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetTableDefinition);
      }
      if (getTableDefinitions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetTableDefinitions);
      }
      if (getRecordCount_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRecordCount);
      }
      if (getRecords_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetRecords);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(YaormMainController other) {
      if (other == null) {
        return;
      }
      if (other.getSchemas_ != null) {
        if (getSchemas_ == null) {
          getSchemas_ = new global::Org.Roylance.Yaorm.CommonAction();
        }
        GetSchemas.MergeFrom(other.GetSchemas);
      }
      if (other.getTables_ != null) {
        if (getTables_ == null) {
          getTables_ = new global::Org.Roylance.Yaorm.CommonAction();
        }
        GetTables.MergeFrom(other.GetTables);
      }
      if (other.getTableDefinition_ != null) {
        if (getTableDefinition_ == null) {
          getTableDefinition_ = new global::Org.Roylance.Yaorm.CommonAction();
        }
        GetTableDefinition.MergeFrom(other.GetTableDefinition);
      }
      if (other.getTableDefinitions_ != null) {
        if (getTableDefinitions_ == null) {
          getTableDefinitions_ = new global::Org.Roylance.Yaorm.CommonAction();
        }
        GetTableDefinitions.MergeFrom(other.GetTableDefinitions);
      }
      if (other.getRecordCount_ != null) {
        if (getRecordCount_ == null) {
          getRecordCount_ = new global::Org.Roylance.Yaorm.CommonAction();
        }
        GetRecordCount.MergeFrom(other.GetRecordCount);
      }
      if (other.getRecords_ != null) {
        if (getRecords_ == null) {
          getRecords_ = new global::Org.Roylance.Yaorm.CommonAction();
        }
        GetRecords.MergeFrom(other.GetRecords);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (getSchemas_ == null) {
              getSchemas_ = new global::Org.Roylance.Yaorm.CommonAction();
            }
            input.ReadMessage(getSchemas_);
            break;
          }
          case 18: {
            if (getTables_ == null) {
              getTables_ = new global::Org.Roylance.Yaorm.CommonAction();
            }
            input.ReadMessage(getTables_);
            break;
          }
          case 26: {
            if (getTableDefinition_ == null) {
              getTableDefinition_ = new global::Org.Roylance.Yaorm.CommonAction();
            }
            input.ReadMessage(getTableDefinition_);
            break;
          }
          case 34: {
            if (getTableDefinitions_ == null) {
              getTableDefinitions_ = new global::Org.Roylance.Yaorm.CommonAction();
            }
            input.ReadMessage(getTableDefinitions_);
            break;
          }
          case 42: {
            if (getRecordCount_ == null) {
              getRecordCount_ = new global::Org.Roylance.Yaorm.CommonAction();
            }
            input.ReadMessage(getRecordCount_);
            break;
          }
          case 50: {
            if (getRecords_ == null) {
              getRecords_ = new global::Org.Roylance.Yaorm.CommonAction();
            }
            input.ReadMessage(getRecords_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
